Fix matrix empty path

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -236,8 +236,14 @@ jobs:
         id: version
         run: |
           SHA=$(git rev-parse --short HEAD)
-          IMAGE_NAME=$(basename $(dirname ${{ matrix.image_path }}))"-"$(basename ${{ matrix.image_path }})
-          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
+          if [[ -n "${{ matrix.image_path }}" ]]; then
+            # Only try to generate image name if matrix path is not empty
+            IMAGE_NAME=$(basename $(dirname "${{ matrix.image_path }}"))"-"$(basename "${{ matrix.image_path }}")
+            echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
+          else
+            echo "::error ::No image path provided in matrix"
+            exit 1
+          fi
           echo "image_tag=${SHA}" >> $GITHUB_OUTPUT
           echo "sha=${SHA}" >> $GITHUB_OUTPUT
       - name: Generate build contexts
